export const LEVELS = [
  // Level 1 - Tutorial (Easy)
  [
    '                                                                                ',
    '                                                                                ',
    '                                                                                ',
    '                                                                                ',
    '                                                                                ',
    '                                                                  xxx           ',
    '                                                   xx      xx    xx!xx          ',
    '                                    o o      xx                  x!!!x          ',
    '                                                                 xx!xx          ',
    '                                   xxxxx                          xvx           ',
    '                                                                            xx  ',
    '  xx                                      o o                                x  ',
    '  x                     o                                                    x  ',
    '  x                                      xxxxx                             o x  ',
    '  x          xxxx       o                                                    x  ',
    '  x  @       x  x                                                xxxxx       x  ',
    '  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ',
    '                              x   x                  x     x                    ',
    '                              x!!!x                  x!!!!!x                    ',
    '                              xxxxx                  xxxxxxx                    ',
  ],
  // Level 2 - Introducing Moving Lava (Medium)
  [
    '                                                                                ',
    '                                      x!!x                        xxxxx         ',
    '                                      x!!x                     xxxx   xxxx      ',
    '                                      x!!xxxxxxxxxx           xx         xx     ',
    '                                      xx!!!!!!!!!!xx         x             x    ',
    '                                       xxxxxxxxxx!!x         x   o   o      x   ',
    '                                                xx!x         x              x   ',
    '                                                 x!x         x     x   x    x   ',
    '                                                 xvx         xx  |   |   |  xx  ',
    '                                                              xx!!!!!!!!!!!xx   ',
    '                                                               xxxx!!!!!xxxx    ',
    '                                               x     x            xxxxxxx       ',
    '                                               x     x                          ',
    '                                               x     x                          ',
    '                                               x     x      o  o     x   x      ',
    '               xxxxxxx        xxx   xxx        x     x               x   x      ',
    '              xx     xx         x   x          x     x     xxxxxx    x   x      ',
    '             xx       xx        x o x          x    xx               x   x      ',
    '     @       x         x        x   x          x     x               x   x      ',
    '    xxx      x         x        x   x          x     x               x   xxxxx  ',
    '    x x      x         x       xx o xx         x     x               x     o    ',
    '!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!     x     =    ',
    '!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!    xxxxxxxxx  ',
  ],
  // Level 3 - Complex Jumps (Medium-Hard)
  [
    '                                                                                ',
    '                                        o                                       ',
    '                                        x                                       ',
    '                                        x                                       ',
    '                                       xxx                                      ',
    '                                       x x                 !!!        !!!  xxx  ',
    '                                       x x                 !x!        !x!       ',
    '                                     xxx xxx                x          x        ',
    '                                      x   x                 x   oooo   x   xxx  ',
    '                                      x   x                 x          x  x!!!x ',
    '                                      x   x                 xxxxxxxxxxxx   xxx  ',
    '                                     xx   xx      x   x      x                  ',
    '                                      x   xxxxxxxxx   xxxxxxxx              x x ',
    '                                      x   x           x                    x!!!x',
    '                                      x   x           x                     xxx ',
    '                                     xx   xx          x                         ',
    '                                      x   x= = = =    x            xxx          ',
    '                                      x   x           x           x!!!x         ',
    '                                      x   x    = = = =x     o      xxx     xxx  ',
    '                                     xx   xx          x                   x!!!x ',
    '                              o   o   x   x           x     x              xxv  ',
    '                                      x   x           x              x          ',
    '                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x          ',
    '                             x xxx x x xxx x          x!!!!!!!!!!!!!!x          ',
    '                             x             x   xxxxxxxxxxxxxxxxxxxxxxx          ',
    '  xxx                         x     x     x                               xxx   ',
    '  x x                         x    xxx    x                              x!!!x  ',
    '  x                           x    xxx    xxxxxxx              xxxxx      xxx   ',
    '  x                           x           x                    x   x            ',
    '  x                           xx          x                    x x x            ',
    '  x                                       x       |xxxx|      xxx xxx           ',
    '  x                xxx             o o    x                    x         xxx    ',
    '  x               xxxxx       xx          x                   xxx       x!!!x   ',
    '  x      @          x         x    xxx    x                   x x        xxx    ',
    '  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x  x oo x    x oo  xx xx              ',
    '                                          x!!x    x!!!!x    xx   xx             ',
    '                                          xxxxxxxxxxxxxxxxxxxxx   xxxxx         ',
  ],
  // Level 4 - Speed Challenge (Hard)
  [
    '                                                                            ',
    '                                                                    xxx x   ',
    '                                                                        x   ',
    '                                                                    xxxxx   ',
    '                          o                                         x       ',
    '                                                                    x xxx   ',
    '                   xxx                                         o o oxxx x   ',
    '       !  o  !                                                          x   ',
    '       x     x                                  xxxxx xxxxx xxxxx xxxxx    ',
    '       x= o  x            x                     x   x x   x x   x x        ',
    '       x     x                                  xxx x xxx x xxx x xxxxx    ',
    '       !  o  !            o                       x x   x x   x x     x    ',
    '                                              xxxx xxxxx xxxxx xxxxxxx      ',
    '          o              xxx                                                ',
    '                                                  xx                        ',
    '                                                                            ',
    '                   xxx         xxx            xx                            ',
    '                                                                            ',
    '                          o                                 x      x        ',
    '             xxx         xxx         xxx                                    ',
    '                                                  ||                        ',
    '  xxxxxxxxxxx                                                               ',
    '  x         x o xxxxxxxxx o xxxxxxxxx o xx                                  ',
    '  x         x   x       x   x       x   x                 ||            x   ',
    '  x  @      xxxxx   o   xxxxx   o   xxxxx                                   ',
    '  xxxxxxx                                     xxxxx       xx     xx     xxx ',
    '        x=                  =                =x   x                     xxx ',
    '        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!xxx!',
    '                                                  xxxxxxxxxxxxxxxxxxxxxxxxx',
  ],
  // Level 5 - Precision Platform (Hard)
  [
    '                                                                                ',
    '                                                                    o           ',
    '                                                                    x           ',
    '                                                                   xxx          ',
    '                                                                   x x      xxx ',
    '                                                                 xxx xxx    x!x ',
    '                                                                  x   x     x!x ',
    '                                                o                 x   x     x!x ',
    '                                                                xxx   xxx   x!x ',
    '                                               xxx                x   x     x!x ',
    '                                              x!!!x              xx   xx    x!x ',
    '                                               xxx                x   x     xvx ',
    '                                                                 xx   xx        ',
    '                                            o  o  o  o            x   x         ',
    '                                                                 xx   xx        ',
    '                                           x   x   x   x          x   x         ',
    '                                                                 xx   xx        ',
    '                              o                                   x   x         ',
    '                              x                                  xx   xx        ',
    '                             xxx                                  x   x         ',
    '                            x!!!x           !!!        !!!       xx   xx        ',
    '                             xxx            !x!        !x!        x   x         ',
    '                                             x          x        xx   xx        ',
    '                         o                   x   oooo   x         x   x         ',
    '                         x                   x          x        xx   xx        ',
    '                        xxx                  xxxxxxxxxxxx         x   x         ',
    '                       x!!!x   |xxxx|                            xx   xx        ',
    '                        xxx                                       x   x         ',
    '                                                                 xx   xx        ',
    '                    = = = =    x                                  x   x         ',
    '                                                                 xx   xx        ',
    '  @                                                               x   x         ',
    '  x           xxx              x            xxx                  xx   xx        ',
    '  x          x!!!x                         x!!!x                  x   x= = = =  ',
    '  xxxx        xxx        o o  x!!!!!!!!     xxx       xxx        xx   xx        ',
    '     x                        x!!!!!!!!              x!!!x        x   x         ',
    '     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxx xxxxxxxxx   xxxxxxxxx ',
  ],
  // Level 6 - Maze Challenge (Very Hard)
  [
    '                                                                                ',
    '                                                                o           xxx ',
    '                                                                x           x x ',
    '                                                               xxx          x x ',
    '                                                              x!!!x         x x ',
    '                                                               xxx          x x ',
    '                                                                            x x ',
    '                            o       o       o                               x x ',
    '                            x       x       x                               xvx ',
    '                           xxx     xxx     xxx                                  ',
    '                          x!!!x   x!!!x   x!!!x         xxx       xxx          ',
    '                           xxx     xxx     xxx          x x       x x          ',
    '                                                         x         x           ',
    '       xxx                                               xx        x           ',
    '       x x                                               x         x           ',
    '       x         o                                       x         x           ',
    '       x         x       !!!        !!!                  x         x           ',
    '       x        xxx      !x!        !x!                  x         x           ',
    '       x       x!!!x      x          x                   xxxxxxxxx x           ',
    '       x        xxx       x   oooo   x     |xxxx|            o     x           ',
    '       x                  x          x                       x     xxxxx       ',
    '       x                  xxxxxxxxxxxx                      xxx        x       ',
    '       x    x   x                                          x!!!x       x       ',
    '       xxxxxx   xxxxxx                x               x     xxx        x       ',
    '                     x                                                 x       ',
    '                     x                                               = x       ',
    '                     x     = = = =    x                                x       ',
    '                     x                                                 x       ',
    '                     x                x                                x       ',
    '                     xxxxxx                                     o      x       ',
    '                          x                                     x      x       ',
    '  @                       x              = x                   xxx     x       ',
    '  x               o       x                                   x!!!x    x       ',
    '  x               x       x                x                   xxx     x       ',
    '  xxxx           xxx      x!!!!!!!!                                    x       ',
    '     x          x!!!x     x!!!!!!!!        x                           x       ',
    '     xxxxxxxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!',
    '                                                                           !!!!',
  ],
  // Level 7 - Final Boss Level (Expert)
  [
    '                                                                                ',
    '                                                                                ',
    '                                                                  o         o   ',
    '                                                                  x         x   ',
    '                                                                 xxx       xxx  ',
    '                                                                x!!!x     x!!!x ',
    '                                                                 xxx       xxx  ',
    '                                                                                ',
    '                  o           o           o                                     ',
    '                  x           x           x                                     ',
    '                 xxx         xxx         xxx                                    ',
    '                x!!!x       x!!!x       x!!!x         xxx       xxx       xxx  ',
    '                 xxx         xxx         xxx          x x       x x       x x  ',
    '                                                       x         x         x    ',
    '                                                       xx        x         x    ',
    '    !!!                                                x         x         x    ',
    '    !x!            = = = =         = = = =             x         x         x    ',
    '     x                                                 x         x         x    ',
    '     x   oooo                             oooo         xxxxxxxxx x       = x    ',
    '     x                |xxxx|                           o     o   x         x    ',
    '     xxxxxxxxxxxx                                      x     x   xxxxx     x    ',
    '                                                      xxx   xxx      x     x    ',
    '         x   x                   x       x           x!!!x x!!!x     x     x    ',
    '         x   x                                        xxx   xxx      x     x    ',
    '  xxxxxxxx   xxxxxx         = = x = = =                             = x = = x   ',
    '                  x                                                   x     x   ',
    '                  x              x                                    x     x   ',
    '                  x                       x                   o       x     x   ',
    '                  x       |xxxx|                              x       x     x   ',
    '                  x                       x                  xxx      x     x   ',
    '                  x              x                          x!!!x     x     x   ',
    '                  xxxxxxx                 x          o       xxx      x     x   ',
    '  @                     x                                    x        x     x   ',
    '  x          o          x        x               = = x = =  xxx       x     x   ',
    '  x          x          x                          x        x x       x     x   ',
    '  xxxx      xxx         x!!!!!   x   !!!!!!!!!     xxxxxxxxxx xxxxxxxxx     x   ',
    '     x     x!!!x        x!!!!!       !!!!!!!!!                  o     o     x   ',
    '     xxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x     x     xxxx',
    '                                                            xxxxxxx   xxxx      ',
    '                                                                  xxxxx         ',
  ],
];
